site_name: DataFoundation - Train the Trainer Workshop (L400)
repo_name: "hariramesh9a/datafoundations"
repo_url: "https://github.com/hariramesh9a/datafoundations"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Introduction: 'index.md'
  - Setup: 'Setup/overview/exercise.md'
  - Prepare Knowledge base for RAG Model:
      - 1 - Overview & Architecture: 'preparerag/overview.md'
      - 2 - Knowledge Base for RAG: 'preparerag/kbase.md'
      - Batch Ingestion/Processing & Data Quality:
        - 1 - Overview: ''
        - 2 - Setup: ''
        - 3 - Run: ''
        - 4 - Data Cataloguing: ''  
      - Stream Processing:
        - 1 - Overview: 'streamprocess/overview.md'
        - 2 - Setup: ''
        - 3 - Create a Kinesis Data Stream: 'streamprocess/kds.md' 
        - 4 - Write Data to a Kinesis Data Stream using Amazon Managed Service for Apache Flink Studio Notebook: 'streamprocess/write_data_to_kds.md'
        - 5 - Run: ''  

  - Prompt Engineering: 
      - 1 - Introduction: ''
      - 2 - Lab Setup: ''
 
  - Building/ Finetuning LLM: 
      - 1 - Introduction: ''
      - 2 - Setup DWH: ''
      
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - attr_list
    - md_in_html