site_name: DataFoundation - Train the Trainer Workshop (L400)
repo_name: "hariramesh9a/datafoundations"
repo_url: "https://github.com/hariramesh9a/datafoundations"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Introduction: 'index.md'
  - Setup: 'setup.md'
  - Prepare Knowledge Store for RAG Model:
      - 1 - Overview & Architecture: 'RAG/overview/exercise.md'
      - 2 - Prerequisites: 'RAG/enviornment/exercise.md'
      - 3 - Launching environment: 'RAG/prerequisites/exercise.md'
  
  - Prepare Data Store/ Knowledge Store: 
    - Batch Ingestion/Processing & Data Quality:
      - 1 - Overview: ''
      - 2 - Setup: ''
      - 3 - Run: ''
      - 4 - Data Cataloguing: ''

    - Stream Processing:
      - 1 - Overview: ''
      - 2 - Setup: ''
      - 3 - Run: ''  

  - Prompt Engineering: 
      - 1 - Introduction: ''
      - 2 - Lab Setup: ''
 
  - Building/ Finetuning LLM: 
      - 1 - Introduction: ''
      - 2 - Setup DWH: ''
      
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - attr_list
    - md_in_html